- name: Install useful desktop tools (dnf)
  become: yes
  dnf: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "dnf"
  tags:
    - packages
    - network

- name: Install useful desktop tools (yum)
  become: yes
  yum: name={{ item }} state=present
  with_items: "{{ desktop.tools }}"
  when: ansible_pkg_mgr == "yum"
  tags:
    - packages
    - network

- name: Install user image from Gravatar
  get_url: url=https://s.gravatar.com/avatar/54bfadc28c22bf76402608db646cd031?s=100 dest=~/.face
