---
ansible_connection: local

# Default state for the RPM packages
package_state_default: "present"

# Base packages to be installed everywhere
# For parameters see:
# - http://docs.ansible.com/ansible/dnf_module.html
# - http://docs.ansible.com/ansible/yum_module.html
base_packages:
  # Base
  - { name: "bash-completion", state: "{{ package_state_default }}" }
  - { name: "bash", state: "{{ package_state_default }}" }
  - { name: "bind-utils", state: "{{ package_state_default }}" }
  - { name: "grep", state: "{{ package_state_default }}" }
  - { name: "htop", state: "{{ package_state_default }}" }
  - { name: "links", state: "{{ package_state_default }}" }
  - { name: "mc", state: "{{ package_state_default }}" }
  - { name: "mtr", state: "{{ package_state_default }}" }
  - { name: "mutt", state: "{{ package_state_default }}" }
  - { name: "screen", state: "{{ package_state_default }}" }
  - { name: "sysstat", state: "{{ package_state_default }}" }
  - { name: "tcpdump", state: "{{ package_state_default }}" }
  - { name: "telnet", state: "{{ package_state_default }}" }
  - { name: "tmux", state: "{{ package_state_default }}" }
  - { name: "wget", state: "{{ package_state_default }}" }
  # Git
  - { name: "git", state: "{{ package_state_default }}" }
  - { name: "tig", state: "{{ package_state_default }}" }
  # Vim
  - { name: "ack", state: "{{ package_state_default }}" }
  - { name: "ctags", state: "{{ package_state_default }}" }
  - { name: "vim-enhanced", state: "{{ package_state_default }}" }

# Where Vim plugins live
vim_plugin_base: "~/.vim/bundle"

# Vim plugins to be installed everywhere
# For parameters see:
# - http://docs.ansible.com/ansible/git_module.html
vim_plugins:
  - { repo: "https://github.com/airblade/vim-gitgutter.git", dest: "{{ vim_plugin_base }}/gitgutter" }
  - { repo: "https://github.com/ctrlpvim/ctrlp.vim", dest: "{{ vim_plugin_base }}/ctrlp" }
  - { repo: "https://github.com/docunext/closetag.vim.git", dest: "{{ vim_plugin_base }}/closetag" }
  - { repo: "https://github.com/editorconfig/editorconfig-vim.git", dest: "{{ vim_plugin_base }}/editorconfig" }
  - { repo: "https://github.com/ervandew/supertab.git", dest: "{{ vim_plugin_base }}/supertab" }
  - { repo: "https://github.com/flazz/vim-colorschemes.git", dest: "{{ vim_plugin_base }}/colorschemes" }
  - { repo: "https://github.com/majutsushi/tagbar.git", dest: "{{ vim_plugin_base }}/tagbar" }
  - { repo: "https://github.com/MarcWeber/vim-addon-mw-utils.git", dest: "{{ vim_plugin_base }}/mv-utils" }
  - { repo: "https://github.com/mattn/gist-vim.git", dest: "{{ vim_plugin_base }}/gist" }
  - { repo: "https://github.com/mattn/webapi-vim.git", dest: "{{ vim_plugin_base }}/webapi" }
  - { repo: "https://github.com/mileszs/ack.vim.git", dest: "{{ vim_plugin_base }}/ack" }
  - { repo: "https://github.com/scrooloose/nerdcommenter.git", dest: "{{ vim_plugin_base }}/nerdcommenter" }
  - { repo: "https://github.com/scrooloose/nerdtree.git", dest: "{{ vim_plugin_base }}/nerdtree" }
  - { repo: "https://github.com/scrooloose/syntastic.git", dest: "{{ vim_plugin_base }}/syntastic" }
  - { repo: "https://github.com/sheerun/vim-polyglot.git", dest: "{{ vim_plugin_base }}/polyglot" }
  - { repo: "https://github.com/tmhedberg/matchit.git", dest: "{{ vim_plugin_base }}/matchit" }
  - { repo: "https://github.com/tomtom/tlib_vim.git", dest: "{{ vim_plugin_base }}/tlib" }
  - { repo: "https://github.com/tpope/vim-fugitive.git", dest: "{{ vim_plugin_base }}/fugitive" }
  - { repo: "https://github.com/vim-airline/vim-airline.git", dest: "{{ vim_plugin_base }}/airline" }
  - { repo: "https://github.com/vim-airline/vim-airline-themes.git", dest: "{{ vim_plugin_base }}/airline-themes" }
  - { repo: "https://github.com/vim-php/tagbar-phpctags.vim.git", dest: "{{ vim_plugin_base }}/tagbar-phpctags" }
  - { repo: "https://github.com/vim-scripts/CSApprox.git", dest: "{{ vim_plugin_base }}/CSApprox" }
  - { repo: "https://github.com/vim-scripts/jQuery.git", dest: "{{ vim_plugin_base }}/jquery" }
  - { repo: "https://github.com/xolox/vim-misc.git", dest: "{{ vim_plugin_base }}/misc" }
  - { repo: "https://github.com/Xuyuanp/nerdtree-git-plugin.git", dest: "{{ vim_plugin_base }}/nerdtree-git" }

# GUI related packages to be installed on desktops
# For parameters see:
# - http://docs.ansible.com/ansible/dnf_module.html
# - http://docs.ansible.com/ansible/yum_module.html
desktop_packages:
  # Desktop
  - { name: "graphviz", state: "{{ package_state_default }}" }
  - { name: "hexchat", state: "{{ package_state_default }}" }
  - { name: "terminator", state: "{{ package_state_default }}" }
  # GNOME Desktop Manager (systemctl disable lightdm.service && systemctl enable gdm.service)
  - { name: "gdm", state: "{{ package_state_default }}" }
  # MATE Desktop Manager
  - { name: "mate-screenshot", state: "{{ package_state_default }}" }
  - { name: "eom", state: "{{ package_state_default }}" }
  # i3 Window Manager
  - { name: "i3", state: "{{ package_state_default }}" }
  - { name: "i3status", state: "{{ package_state_default }}" }
  - { name: "i3lock", state: "{{ package_state_default }}" }
  - { name: "dmenu", state: "{{ package_state_default }}" }
  - { name: "feh", state: "{{ package_state_default }}" }
  - { name: "xcompmgr", state: "{{ package_state_default }}" }
  - { name: "xorg-x11-xkb-utils", state: "{{ package_state_default }}" }
  - { name: "network-manager-applet", state: "{{ package_state_default }}" }
  - { name: "alsa-utils", state: "{{ package_state_default }}" }
  - { name: "pulseaudio-utils", state: "{{ package_state_default }}" }
  - { name: "xbacklight", state: "{{ package_state_default }}" }
  - { name: "arandr", state: "{{ package_state_default }}" }

# GUI related files to download on desktops
# For parameters see:
# - http://docs.ansible.com/ansible/get_url_module.html
desktop_downloads:
  # Gravatar image login/screensaver lock/etc
  - { url: "https://s.gravatar.com/avatar/54bfadc28c22bf76402608db646cd031?s=100", dest: "~/.face" }

# Development packages to be installed on development workstations
# For parameters see:
# - http://docs.ansible.com/ansible/dnf_module.html
# - http://docs.ansible.com/ansible/yum_module.html
devel_packages:
  # PHP
  - { name: "php", state: "{{ package_state_default }}" }
  - { name: "php-bcmath", state: "{{ package_state_default }}" }
  - { name: "php-cli", state: "{{ package_state_default }}" }
  - { name: "php-common", state: "{{ package_state_default }}" }
  - { name: "php-gd", state: "{{ package_state_default }}" }
  - { name: "php-intl", state: "{{ package_state_default }}" }
  - { name: "php-ldap", state: "{{ package_state_default }}" }
  - { name: "php-mbstring", state: "{{ package_state_default }}" }
  - { name: "php-mcrypt", state: "{{ package_state_default }}" }
  - { name: "php-mysqlnd", state: "{{ package_state_default }}" }
  - { name: "php-opcache", state: "{{ package_state_default }}" }
  - { name: "php-pdo", state: "{{ package_state_default }}" }
  - { name: "php-pecl-apcu", state: "{{ package_state_default }}" }
  - { name: "php-pecl-xdebug", state: "{{ package_state_default }}" }
  - { name: "php-process", state: "{{ package_state_default }}" }
  - { name: "php-soap", state: "{{ package_state_default }}" }
  - { name: "php-xml", state: "{{ package_state_default }}" }
  # MySQL/MariaDB
  - { name: "mariadb", state: "{{ package_state_default }}" }
  - { name: "mariadb-server", state: "{{ package_state_default }}" }

# geerlingguy.composer : Put in /usr/bin/
composer_path: /usr/bin/composer
# geerlingguy.composer : Keep updated to prevent outdated warnings
composer_keep_updated: true

