---
- name: Copy dotfiles
  copy: src={{ item }} dest={{ ansible_user_dir }}/.{{ item | basename }}
  with_fileglob:
    - ./dotfiles/*
  tags:
    - files

- name: Ensure bin/ folder exists
  file: path={{ ansible_user_dir}}/bin state=directory
  tags:
    - files

- name: Ensure ~/Work folder exists
  file: path=~/Work state=directory
  tags:
    - files

- name: Copy bin/ files
  copy: src={{ item }} dest={{ ansible_user_dir }}/bin/{{ item | basename }}
  with_fileglob:
    - ./bin/*
  tags:
    - files

- name: Install useful tools (dnf)
  sudo: yes
  dnf: name={{ item }} state=present
  with_items: "{{ dotfiles.dependencies }}"
  when: ansible_pkg_mgr == "dnf"
  tags:
    - packages
    - network

- name: Install useful tools (yum)
  sudo: yes
  yum: name={{ item }} state=present
  with_items: "{{ dotfiles.dependencies }}"
  when: ansible_pkg_mgr == "yum"
  tags:
    - packages
    - network

